@startuml
actor User
participant GDM
box SSSD
participant pam_sss
participant "PAM responder"
end box

GDM -> User: Login prompt
User -> GDM: Input username
GDM -> pam_sss: pam_start(service, user, conv, pamh)
GDM -> pam_sss: pam_authenticate(pamh, flags, argc, argv)
pam_sss -> "PAM responder": sss_cli_send_req()
note over "PAM responder": Resolves the username and obtains, among other things,\nthe available authentication methods and the prompting\nstrings.

"PAM responder" -> "PAM responder": format_json(auth_mechanisms, prompts)
"PAM responder" -> pam_sss: sss_cli_recv_rep(..., json_msg)
pam_sss -> GDM: pam_conv(1, message, &reply, appdata_ptr)
GDM -> User: Prompt user credentials\nand available authentication\nmechanisms
User -> GDM: Choose authentication mechanism and input data
GDM -> GDM: format_json(auth_selection, data)
GDM -> pam_sss: return pam_conv(reply)

@enduml
